[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Tốc độ nạp code
upload_speed = 921600

; Tốc độ Serial Monitor
monitor_speed = 115200

; Bộ lọc debug (Rất quan trọng)
monitor_filters = 
	esp32_exception_decoder
	time
	colorize

; Cờ biên dịch cho FreeRTOS
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D CONFIG_FREERTOS_HZ=1000

; TẢI THƯ VIỆN CHO MÀN HÌNH OLED
lib_deps =
	adafruit/Adafruit SSD1306 @ ^2.5.7
	adafruit/Adafruit GFX Library @ ^1.11.5