[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Tốc độ nạp code (tăng lên để tiết kiệm thời gian chờ)
upload_speed = 921600

; Tốc độ Serial Monitor (Bắt buộc phải khớp với Serial.begin(115200) trong main.cpp)
monitor_speed = 115200

; BỘ LỌC DEBUG (Vũ khí quan trọng nhất khi làm RTOS)
monitor_filters = 
	esp32_exception_decoder  ; Tự động dịch mã lỗi Guru Meditation Error thành số dòng code bị lỗi
	time                     ; Thêm nhãn thời gian (timestamp) vào đầu mỗi dòng log để kiểm tra độ trễ (latency) của các Task
	colorize                 ; Tô màu log để dễ phân biệt các cảnh báo (Warning/Error)

; CỜ BIÊN DỊCH
build_flags = 
	-D CORE_DEBUG_LEVEL=3    ; Mức độ log: 0=None, 1=Error, 2=Warn, 3=Info, 4=Debug, 5=Verbose
	-D CONFIG_FREERTOS_HZ=1000 ; Ép xung nhịp tick của FreeRTOS lên 1000Hz (1 tick = 1ms) để tính toán thời gian mượt mà hơn