[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
	bodmer/TFT_eSPI @ ^2.5.43
	esphome/ESP32-audioI2S @ 2.3.0

build_flags = 
	-D USER_SETUP_LOADED=1
	-D ST7735_DRIVER=1
	-D ST7735_BLACKTAB=1
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_WIDTH=128
	-D TFT_HEIGHT=160
	; -- CẬP NHẬT CHÂN MỚI Ở ĐÂY --
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_CS=5
	-D TFT_DC=19
	-D TFT_RST=17
	-D LOAD_GLCD=1
	-D SPI_FREQUENCY=27000000

monitor_filters = send_on_enter, echo
board_build.filesystem = littlefs   ; [MỚI] Kích hoạt phân vùng Root FS